# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import workspace_pb2 as workspace__pb2


class workspaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserSignup = channel.unary_unary(
                '/unary.workspace/UserSignup',
                request_serializer=workspace__pb2.UserData.SerializeToString,
                response_deserializer=workspace__pb2.UserDataResponse.FromString,
                )


class workspaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserSignup(self, request, context):
        """Workspace rpc declaration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_workspaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserSignup': grpc.unary_unary_rpc_method_handler(
                    servicer.UserSignup,
                    request_deserializer=workspace__pb2.UserData.FromString,
                    response_serializer=workspace__pb2.UserDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.workspace', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class workspace(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserSignup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.workspace/UserSignup',
            workspace__pb2.UserData.SerializeToString,
            workspace__pb2.UserDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
