# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workspace.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fworkspace.proto\x12\x05unary\"\x18\n\x08UserData\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\x10UserDataResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\x45\n\tworkspace\x12\x38\n\nUserSignup\x12\x0f.unary.UserData\x1a\x17.unary.UserDataResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workspace_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERDATA._serialized_start=26
  _USERDATA._serialized_end=50
  _USERDATARESPONSE._serialized_start=52
  _USERDATARESPONSE._serialized_end=102
  _WORKSPACE._serialized_start=104
  _WORKSPACE._serialized_end=173
# @@protoc_insertion_point(module_scope)
